#! perl

sub on_user_command {
	my ($self, $cmd) = @_;
	if ($cmd eq "opacity:down") {
		my $dummy = `picom-trans -c -o 80` ;
	} elsif ($cmd eq "opacity:up") {
		my $dummy = `picom-trans -c -o 100` ;
	}
}
